/**
 * AUTO-GENERATED CATEGORY BACKGROUND IMAGES
 * This file was generated by scripts/generateCategoryImages.ts
 * using the Pexels API.
 */

export const CATEGORY_BACKGROUND_IMAGES: Record<string, string> = {
  "Chicken": "https://images.pexels.com/photos/927805/pexels-photo-927805.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "Beef": "https://images.pexels.com/photos/927805/pexels-photo-927805.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "Pork": "https://images.pexels.com/photos/10066717/pexels-photo-10066717.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "Fish": "https://images.pexels.com/photos/8472645/pexels-photo-8472645.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "Seafood": "https://images.pexels.com/photos/28992232/pexels-photo-28992232.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "Vegetarian": "https://images.pexels.com/photos/7214598/pexels-photo-7214598.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  "Vegan": "https://images.pexels.com/photos/7214598/pexels-photo-7214598.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"
};
