// Centralized color + background image tokens for the app.
// This file is intentionally simple – values can be tweaked for branding,
// but the shape of the exports should remain stable.

export const COLORS = {
  // Core brand shades
  primary: "#ff6b3c",
  primaryDark: "#e45a2f",
  primaryGradient: ["#ff6b3c", "#ff9f43"],

  // Surfaces & backgrounds
  background: "#020617",
  bg: "#020617",

  // Text colors
  textPrimary: "#f9fafb",
  textMain: "#f9fafb",
  textMuted: "#9ca3af",

  // Borders / outlines
  borderUnfocused: "rgba(148, 163, 184, 0.7)",

  // Utility colors
  white: "#ffffff",
  black: "#000000",
  error: "#ef4444",
  ratingGold: "#facc15",
  accent: "#4dd0e1",
} as const;

// Hero background images for key screens.
// These can be replaced with URLs generated by scripts/generateUiBackgroundImages.ts.
export const COOKING_BACKGROUND_IMAGE: string =
  "https://images.pexels.com/photos/6287529/pexels-photo-6287529.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1200&q=80";

export const SEARCH_BACKGROUND_IMAGE: string =
  "https://images.pexels.com/photos/3296541/pexels-photo-3296541.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1200&q=80";

export const PROFILE_BACKGROUND_IMAGE: string =
  "https://images.pexels.com/photos/3298180/pexels-photo-3298180.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1200&q=80";

// Re-export generated category backgrounds so consumers can import from
// "@/constants/colors" only.
export { CATEGORY_BACKGROUND_IMAGES } from "./category-backgrounds.generated";
