import dotenv from "dotenv";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

dotenv.config();

// Support ESM execution (Node/ts-node) by deriving __dirname from import.meta.url
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PEXELS_API_KEY = process.env.PEXELS_API_KEY;

if (!PEXELS_API_KEY) {
  console.error(
    "Missing PEXELS_API_KEY in environment. Please set it in your .env file."
  );
  process.exit(1);
}

interface PexelsPhotoSrc {
  original: string;
  large2x: string;
  large: string;
  medium: string;
  small: string;
  portrait: string;
  landscape: string;
  tiny: string;
}

interface PexelsPhoto {
  id: number;
  url: string;
  src: PexelsPhotoSrc;
}

interface PexelsSearchResponse {
  photos: PexelsPhoto[];
}

type UiBackgroundKey = "home" | "search" | "profile";

const UI_BACKGROUND_QUERIES: Record<UiBackgroundKey, string> = {
  home: "modern cooking kitchen hero dark background shallow depth of field",
  search: "flat lay ingredients on dark table minimal search background",
  profile: "chef portrait in kitchen warm light bokeh background",
};

async function fetchBackgroundImage(query: string): Promise<string | null> {
  const encoded = encodeURIComponent(query);
  const url = `https://api.pexels.com/v1/search?query=${encoded}&per_page=1`;

  const response = await fetch(url, {
    headers: {
      Authorization: PEXELS_API_KEY as string,
    },
  });

  if (!response.ok) {
    console.warn(
      `Pexels request failed for "${query}" with status ${response.status}`
    );
    return null;
  }

  const data = (await response.json()) as PexelsSearchResponse;
  const photo = data.photos?.[0];

  if (!photo || !photo.src) {
    console.warn(`No photo found for "${query}"`);
    return null;
  }

  // Prefer landscape for full-width backgrounds
  return photo.src.landscape || photo.src.large || photo.src.medium || null;
}

async function main() {
  console.log("Generating UI background images (home, search, profile) from Pexels...");

  const results: Partial<Record<UiBackgroundKey, string>> = {};

  for (const key of Object.keys(UI_BACKGROUND_QUERIES) as UiBackgroundKey[]) {
    const query = UI_BACKGROUND_QUERIES[key];
    console.log(`Fetching "${key}" background with query: ${query}`);
    try {
      const imageUrl = await fetchBackgroundImage(query);
      if (imageUrl) {
        results[key] = imageUrl;
      } else {
        results[key] = "";
      }
    } catch (error) {
      console.error(`Error fetching background for "${key}":`, error);
      results[key] = "";
    }
  }

  const outputPath = path.resolve(
    __dirname,
    "../constants/ui-backgrounds.generated.ts"
  );

  const fileContents = `/**
 * AUTO-GENERATED UI BACKGROUND IMAGES
 * This file was generated by scripts/generateUiBackgroundImages.ts
 * using the Pexels API.
 *
 * You can copy these URLs into your theme file (e.g., colors.ts) for:
 * - COOKING_BACKGROUND_IMAGE
 * - SEARCH_BACKGROUND_IMAGE
 * - PROFILE_BACKGROUND_IMAGE
 */

export const COOKING_BACKGROUND_IMAGE = ${
    results.home && results.home.trim().length > 0
      ? `"${(results.home ?? "").replace(/"/g, '\\"')}";`
      : '"";'
  }

export const SEARCH_BACKGROUND_IMAGE = ${
    results.search && results.search.trim().length > 0
      ? `"${(results.search ?? "").replace(/"/g, '\\"')}";`
      : '"";'
  }

export const PROFILE_BACKGROUND_IMAGE = ${
    results.profile && results.profile.trim().length > 0
      ? `"${(results.profile ?? "").replace(/"/g, '\\"')}";`
      : '"";'
  }
`;

  fs.writeFileSync(outputPath, fileContents, { encoding: "utf8" });

  console.log(`UI background mappings written to ${outputPath}`);
  console.log(
    "Open that file and copy the URLs into COOKING_BACKGROUND_IMAGE, SEARCH_BACKGROUND_IMAGE, and PROFILE_BACKGROUND_IMAGE in constants/colors.ts."
  );
}

void main().catch((error) => {
  console.error("Error running generateUiBackgroundImages:", error);
  process.exit(1);
});


